version: '3.8'

services:
  # --- БЭК ---
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/games_db?sslmode=disable

  # --- БД ---
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=games_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # --- ФРОНТ ---
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - app